format = """
[](#789DEC)\
$username\
[](bg:#A583DE fg:#789DEC)\
$directory\
[](bg:#8EB376 fg:#A583DE)\
$git_branch\
$git_status\
[ ](fg:#8EB376)\
$aws\
$dart\
$docker_context\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$lua\
$nodejs\
$nim\
$python\
$rust\
$scala\
$time\
$line_break\
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[aws]
symbol = " "

[buf]
symbol = " "

[c]
symbol = " "

[character]
success_symbol = "[➜](bold cyan)"
error_symbol = "[➜](bold 166)"
vimcmd_symbol = "[➜](bold cyan)"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
style = "bg:#A583DE fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "
style = "bg:#8EB376"
format = '[[ $symbol $branch ](bg:#8EB376 fg:#000000)]($style)'

[git_status]
style = "fg:#8EB376"
format = '[[( $all_status$ahead_behind )](bg:#8EB376 fg:#000000)]($style)'

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "
format = 'via [${symbol}${pyenv_prefix}(${version} )]($style)'

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#FF8A9D"

[username]
show_always = true
style_user = "bg:#789DEC fg:#000000"
style_root = "bg:#789DEC fg:#000000"
format = '[ $user ]($style)'
