# https://github.com/catppuccin/helix/blob/main/themes/default/catppuccin_mocha.toml
theme = "catppuccin_mocha"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
# select = "block"
