format = """
[](#000000)\
$username\
[](bg:#404040 fg:#000000)\
$directory\
[](bg:#808080 fg:#404040)\
$git_branch\
$git_status\
[ ](fg:#808080)\
$aws\
$docker_context\
$nix_shell\
$elixir\
$golang\
$java\
$lua\
$nodejs\
$python\
$rust\
$time\
$line_break\
$character
"""

# Disable the blank line at the start of the prompt
add_newline = true

[aws]
symbol = " "

[character]
success_symbol = "[>](bold #000000)"
error_symbol = "[x](bold #000000)"
vimcmd_symbol = "[_](bold #000000)"

[directory]
style = "bg:#404040 fg:#f0f0f0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[docker_context]
style = "fg:#"
symbol = " "

[elixir]
symbol = " "

[git_branch]
symbol = " "
style = "bg:#808080"
format = '[[ $symbol $branch ](bg:#808080 fg:#f0f0f0)]($style)'

[git_status]
style = "fg:#808080"
format = '[[( $all_status$ahead_behind )](bg:#808080 fg:#f0f0f0)]($style)'

[golang]
style = "fg:#000000"
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[nix_shell]
symbol = " "
impure_msg = ""
pure_msg = ""

[nodejs]
symbol = " "

[python]
symbol = " "
style = "fg:#000000"
format = 'via [${symbol}${pyenv_prefix}(${version} )]($style)'

[rust]
symbol = " "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#000000"

[username]
format = '[ $user ]($style)'
show_always = true
style_root = "bg:#000000 fg:#f0f0f0"
style_user = "bg:#000000 fg:#f0f0f0"
