###########
# General #
###########

config-version = 2
start-at-login = true

# Tile windows by default.
default-root-container-layout = 'tiles'

# Side-by-side layout on normal widescreen displays.
default-root-container-orientation = 'auto'

# Auto center the mouse pointer at the window being focused
on-focus-changed = ['move-mouse window-lazy-center']

############
# Monitors #
############

# Set external monitor (main) as primary display
[workspace-to-monitor-force-assignment]
1 = ['main', 'built-in']
2 = ['main', 'built-in']
3 = ['main', 'built-in']
4 = ['main', 'built-in']
5 = ['main', 'built-in']
6 = ['main', 'built-in']
7 = ['main', 'built-in']
8 = ['main', 'built-in']
9 = ['main', 'built-in']


########
# Gaps #
########

# 1px gap between tiled windows.
[gaps]
inner.horizontal = 0
inner.vertical = 1
outer.left = 0
outer.right = 0
outer.top = 0
outer.bottom = 0


################
# Window Rules #
################

[[on-window-detected]]
if.app-id = "com.valvesoftware.steam"
run = "layout floating"

[[on-window-detected]]
if.app-id = "com.libretro.dist.RetroArch"
run = "layout floating"

# Reload config using Cmd + Ctrl + -
[mode.main.binding]
cmd-ctrl-minus = 'reload-config'


##########################
# Keybindings - Vertical #
##########################

# Ghostty
cmd-0 = [
  'workspace 1',
  'exec-and-forget open -a Ghostty',
  'move-node-to-workspace 1',
]

# Safari
cmd-1 = [
  'workspace 2',
  'exec-and-forget open -a Safari',
  'move-node-to-workspace 2',
]

# ChatGPT Classic
cmd-2 = [
  'workspace 2',
  'exec-and-forget open -a "ChatGPT Classic"',
  'move-node-to-workspace 2'
]

# Finder
cmd-3 = [
  'workspace 3',
  'exec-and-forget open -a Finder',
  'move-node-to-workspace 3',
]

# Music
cmd-4 = [
  'workspace 4',
  'exec-and-forget open -a Music',
  'move-node-to-workspace 4'
]

# YouTube
cmd-5 = [
  'workspace 4',
  'exec-and-forget open -a YouTube',
  'move-node-to-workspace 4'
]

# Organize
cmd-minus = [
  'workspace 1',
  'focus --dfs-index 0',
  'resize height 880',
]
