set -as terminal-features ",tmux-256color:RGB"
set -g default-terminal "tmux-256color"

# Status bar colors
set -g status-style "bg=#0e1116,fg=#ffffff"

# Copy mode colors
set -g mode-style "bg=#368cf9,fg=#ffffff"

# Enable mouse support
set -g mouse on

# Set terminal history to 10k lines
set -g history-limit 10000

# Clipboard
set -g set-clipboard on
set -g allow-passthrough on

###############
# KEYBINDINGS #
###############

# Prefix
unbind C-b
set -g prefix C-k
bind C-k send-prefix

# Create new window
bind-key j new-window

# Navigate windows
bind-key l next-window
bind-key h previous-window

# Split panes
bind | split-window -h
bind - split-window -v

# Config reloading
bind r source-file ~/.tmux.conf \; display-message "config reloaded!"
