set -as terminal-features ",*:RGB"
set -g default-terminal "tmux-256color"

# Status bar colors
set -g status-style "bg=#0e1116,fg=#ffffff"

# Copy mode colors
set -g mode-style "bg=#368cf9,fg=#ffffff"

# Enable mouse support
set -g mouse on

# Set terminal history to 10k lines
set -g history-limit 10000

# Clipboard
set -g set-clipboard on
set -g allow-passthrough on


###############
# KEYBINDINGS #
###############

# Prefix
unbind C-b
set -g prefix C-k
bind C-k send-prefix

# Create new window
# bind-key j new-window -c "#{pane_current_path}" # new window opens on the current directory
bind-key j new-window # new window opens on the home directory

# Navigate windows
bind-key h previous-window
bind-key l next-window

# Navigate panes
# bind-key -n C-\; select-pane -D

# Copy selection to macOS clipboard
bind-key -T copy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"

# Config reloading
bind r source-file ~/.tmux.conf \; display-message "config reloaded!"


##########
# LAYOUT #
##########

# Set panes
# set-hook -g after-new-session 'send-keys "nvim" C-m; split-window -v -p 25'
# set-hook -g after-new-window 'send-keys "nvim" C-m; split-window -v -p 25'
